[package]
name = "roguelike-rust"
version = "0.1.0"
authors = ["Guillaume Gomez <guillaume.gomez846@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.15"